# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180604_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_token',
            field=models.FloatField(blank=True),
            preserve_default=False,
        ),
    ]
