# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_number_of_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_shop',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
