# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180604_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_token',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
