# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180604_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(blank=True, max_length=200)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Component')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_token',
        ),
    ]
