# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180605_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
